# host/robot_host/base_transport.py
from typing import Callable, Protocol


class BaseTransport(Protocol):
    def set_frame_handler(self, handler: Callable[[bytes], None]) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def send_frame(self, msg_type: int, payload: bytes = b"") -> None: ...
