from robot_host.command.client import AsyncRobotClient
from robot_host.core.event_bus import EventBus


class MotionHostModule:
    """High-level motion helpers (SET_VEL / STOP / ESTOP).

    Wraps the autogenerated cmd_* motion helpers on AsyncRobotClient.
    """

    def __init__(self, bus: EventBus, client: AsyncRobotClient) -> None:
        self._bus = bus
        self._client = client

    async def set_velocity(self, vx: float, omega: float, frame: str = "robot") -> None:
        # Uses generated cmd_set_vel(vx, omega, frame)
        await self._client.cmd_set_vel(
            vx=float(vx),
            omega=float(omega),
            frame=frame,
        )

    async def stop(self) -> None:
        await self._client.cmd_stop()

    async def estop(self) -> None:
        await self._client.cmd_estop()

    async def clear_estop(self) -> None:
        await self._client.cmd_clear_estop()
