from typing import Any
from robot_host.core.client import AsyncRobotClient
from robot_host.core.event_bus import EventBus


class LoggingControlModule:
    """Host-side helper for CMD_SET_LOG_LEVEL.

    Wraps the generated cmd_set_log_level() on AsyncRobotClient.
    """

    def __init__(self, bus: EventBus, client: AsyncRobotClient) -> None:
        self._bus = bus
        self._client = client

    async def set_level(self, level: str = "info") -> None:
        # Use the autogenerated helper instead of hardcoding CMD_*.
        await self._client.cmd_set_log_level(level=level)
