# AUTO-GENERATED BY gen_commands.py — DO NOT EDIT.

from __future__ import annotations
from typing import Any, Optional


class RobotCommandsMixin:
    """
    Auto-generated high-level JSON command helpers.
    Requires that the inheriting client defines:
        async def send_json_cmd(self, type_str: str, payload: dict | None = None) -> None
    """
    async def cmd_set_mode(self, mode: str) -> None:
        """Set the high-level robot mode (e.g., IDLE, ARMED, ACTIVE). (CMD_SET_MODE)"""
        payload: dict[str, Any] = {}
        payload['mode'] = mode
        await self.send_json_cmd('CMD_SET_MODE', payload)

    async def cmd_set_vel(self, vx: float, omega: float, frame: str = 'robot') -> None:
        """Set linear and angular velocity in robot frame. (CMD_SET_VEL)"""
        payload: dict[str, Any] = {}
        payload['vx'] = vx
        payload['omega'] = omega
        payload['frame'] = frame
        await self.send_json_cmd('CMD_SET_VEL', payload)

    async def cmd_stop(self) -> None:
        """Stop all motion (soft stop). (CMD_STOP)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_STOP', payload)

    async def cmd_estop(self) -> None:
        """Emergency stop, immediately disable motion. (CMD_ESTOP)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_ESTOP', payload)

    async def cmd_clear_estop(self) -> None:
        """Clear ESTOP and typically return to IDLE mode. (CMD_CLEAR_ESTOP)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_CLEAR_ESTOP', payload)

    async def cmd_led_on(self) -> None:
        """Turn status LED on. (CMD_LED_ON)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_LED_ON', payload)

    async def cmd_led_off(self) -> None:
        """Turn status LED off. (CMD_LED_OFF)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_LED_OFF', payload)

    async def cmd_gpio_write(self, channel: int, value: int) -> None:
        """Write a digital value to a logical GPIO channel. (CMD_GPIO_WRITE)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        payload['value'] = value
        await self.send_json_cmd('CMD_GPIO_WRITE', payload)

    async def cmd_gpio_read(self, channel: int) -> None:
        """Read a digital value from a logical GPIO channel. (CMD_GPIO_READ)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        await self.send_json_cmd('CMD_GPIO_READ', payload)

    async def cmd_gpio_toggle(self, channel: int) -> None:
        """Toggle a logical GPIO channel. (CMD_GPIO_TOGGLE)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        await self.send_json_cmd('CMD_GPIO_TOGGLE', payload)

    async def cmd_gpio_register_channel(self, channel: int, pin: int, mode: str = 'output') -> None:
        """Register or re-map a logical GPIO channel to a physical pin. (CMD_GPIO_REGISTER_CHANNEL)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        payload['pin'] = pin
        payload['mode'] = mode
        await self.send_json_cmd('CMD_GPIO_REGISTER_CHANNEL', payload)

    async def cmd_pwm_set(self, channel: int, duty: float, freq_hz: Optional[float] = None) -> None:
        """Set PWM duty cycle for a logical channel. (CMD_PWM_SET)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        payload['duty'] = duty
        if freq_hz is not None:
            payload['freq_hz'] = freq_hz
        await self.send_json_cmd('CMD_PWM_SET', payload)

    async def cmd_servo_attach(self, servo_id: int, channel: int, min_us: int = 1000, max_us: int = 2000) -> None:
        """Attach a servo ID to a physical pin. (CMD_SERVO_ATTACH)"""
        payload: dict[str, Any] = {}
        payload['servo_id'] = servo_id
        payload['channel'] = channel
        payload['min_us'] = min_us
        payload['max_us'] = max_us
        await self.send_json_cmd('CMD_SERVO_ATTACH', payload)

    async def cmd_servo_detach(self, servo_id: int) -> None:
        """Detach a servo ID. (CMD_SERVO_DETACH)"""
        payload: dict[str, Any] = {}
        payload['servo_id'] = servo_id
        await self.send_json_cmd('CMD_SERVO_DETACH', payload)

    async def cmd_servo_set_angle(self, servo_id: int, angle_deg: float, duration_ms: int = 0) -> None:
        """Set servo angle in degrees. (CMD_SERVO_SET_ANGLE)"""
        payload: dict[str, Any] = {}
        payload['servo_id'] = servo_id
        payload['angle_deg'] = angle_deg
        payload['duration_ms'] = duration_ms
        await self.send_json_cmd('CMD_SERVO_SET_ANGLE', payload)

    async def cmd_stepper_move_rel(self, motor_id: int, steps: int, speed_steps_s: float = 1000.0) -> None:
        """Move a stepper a relative number of steps. (CMD_STEPPER_MOVE_REL)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        payload['steps'] = steps
        payload['speed_steps_s'] = speed_steps_s
        await self.send_json_cmd('CMD_STEPPER_MOVE_REL', payload)

    async def cmd_stepper_stop(self, motor_id: int) -> None:
        """Immediately stop a stepper motor. (CMD_STEPPER_STOP)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        await self.send_json_cmd('CMD_STEPPER_STOP', payload)

    async def cmd_stepper_enable(self, motor_id: int, enable: bool = True) -> None:
        """Enable or disable a stepper driver (via enable pin). (CMD_STEPPER_ENABLE)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        payload['enable'] = enable
        await self.send_json_cmd('CMD_STEPPER_ENABLE', payload)

    async def cmd_ultrasonic_attach(self, sensor_id: int = 0) -> None:
        """Attach/configure an ultrasonic sensor for the given logical sensor_id. (CMD_ULTRASONIC_ATTACH)"""
        payload: dict[str, Any] = {}
        payload['sensor_id'] = sensor_id
        await self.send_json_cmd('CMD_ULTRASONIC_ATTACH', payload)

    async def cmd_ultrasonic_read(self, sensor_id: int = 0) -> None:
        """Trigger a single ultrasonic distance measurement. (CMD_ULTRASONIC_READ)"""
        payload: dict[str, Any] = {}
        payload['sensor_id'] = sensor_id
        await self.send_json_cmd('CMD_ULTRASONIC_READ', payload)

    async def cmd_telem_set_interval(self, interval_ms: int = 100) -> None:
        """Set telemetry publish interval in milliseconds (0 = disable). (CMD_TELEM_SET_INTERVAL)"""
        payload: dict[str, Any] = {}
        payload['interval_ms'] = interval_ms
        await self.send_json_cmd('CMD_TELEM_SET_INTERVAL', payload)

    async def cmd_set_log_level(self, level: str = 'info') -> None:
        """Set MCU logging verbosity level. (CMD_SET_LOG_LEVEL)"""
        payload: dict[str, Any] = {}
        payload['level'] = level
        await self.send_json_cmd('CMD_SET_LOG_LEVEL', payload)

    async def cmd_encoder_attach(self, encoder_id: int = 0, pin_a: int = 32, pin_b: int = 33) -> None:
        """Attach/configure a quadrature encoder with runtime pins. (CMD_ENCODER_ATTACH)"""
        payload: dict[str, Any] = {}
        payload['encoder_id'] = encoder_id
        payload['pin_a'] = pin_a
        payload['pin_b'] = pin_b
        await self.send_json_cmd('CMD_ENCODER_ATTACH', payload)

    async def cmd_encoder_read(self, encoder_id: int = 0) -> None:
        """Request current tick count for a given encoder. (CMD_ENCODER_READ)"""
        payload: dict[str, Any] = {}
        payload['encoder_id'] = encoder_id
        await self.send_json_cmd('CMD_ENCODER_READ', payload)

    async def cmd_encoder_reset(self, encoder_id: int = 0) -> None:
        """Reset the tick count for a given encoder back to zero. (CMD_ENCODER_RESET)"""
        payload: dict[str, Any] = {}
        payload['encoder_id'] = encoder_id
        await self.send_json_cmd('CMD_ENCODER_RESET', payload)

    async def cmd_dc_set_speed(self, motor_id: int, speed: float) -> None:
        """Set DC motor speed and direction for a given motor ID. (CMD_DC_SET_SPEED)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        payload['speed'] = speed
        await self.send_json_cmd('CMD_DC_SET_SPEED', payload)

    async def cmd_dc_stop(self, motor_id: int) -> None:
        """Stop a DC motor (set speed to zero). (CMD_DC_STOP)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        await self.send_json_cmd('CMD_DC_STOP', payload)

