# AUTO-GENERATED FILE — DO NOT EDIT BY HAND
# Generated from COMMANDS in platform_schema.py

CMD_CLEAR_ESTOP = "CMD_CLEAR_ESTOP"
CMD_DC_SET_SPEED = "CMD_DC_SET_SPEED"
CMD_DC_STOP = "CMD_DC_STOP"
CMD_ENCODER_ATTACH = "CMD_ENCODER_ATTACH"
CMD_ENCODER_READ = "CMD_ENCODER_READ"
CMD_ENCODER_RESET = "CMD_ENCODER_RESET"
CMD_ESTOP = "CMD_ESTOP"
CMD_GPIO_READ = "CMD_GPIO_READ"
CMD_GPIO_REGISTER_CHANNEL = "CMD_GPIO_REGISTER_CHANNEL"
CMD_GPIO_TOGGLE = "CMD_GPIO_TOGGLE"
CMD_GPIO_WRITE = "CMD_GPIO_WRITE"
CMD_LED_OFF = "CMD_LED_OFF"
CMD_LED_ON = "CMD_LED_ON"
CMD_PWM_SET = "CMD_PWM_SET"
CMD_SERVO_ATTACH = "CMD_SERVO_ATTACH"
CMD_SERVO_DETACH = "CMD_SERVO_DETACH"
CMD_SERVO_SET_ANGLE = "CMD_SERVO_SET_ANGLE"
CMD_SET_LOG_LEVEL = "CMD_SET_LOG_LEVEL"
CMD_SET_MODE = "CMD_SET_MODE"
CMD_SET_VEL = "CMD_SET_VEL"
CMD_STEPPER_ENABLE = "CMD_STEPPER_ENABLE"
CMD_STEPPER_MOVE_REL = "CMD_STEPPER_MOVE_REL"
CMD_STEPPER_STOP = "CMD_STEPPER_STOP"
CMD_STOP = "CMD_STOP"
CMD_TELEM_SET_INTERVAL = "CMD_TELEM_SET_INTERVAL"
CMD_ULTRASONIC_ATTACH = "CMD_ULTRASONIC_ATTACH"
CMD_ULTRASONIC_READ = "CMD_ULTRASONIC_READ"

ALL_COMMANDS = [
    CMD_CLEAR_ESTOP,
    CMD_DC_SET_SPEED,
    CMD_DC_STOP,
    CMD_ENCODER_ATTACH,
    CMD_ENCODER_READ,
    CMD_ENCODER_RESET,
    CMD_ESTOP,
    CMD_GPIO_READ,
    CMD_GPIO_REGISTER_CHANNEL,
    CMD_GPIO_TOGGLE,
    CMD_GPIO_WRITE,
    CMD_LED_OFF,
    CMD_LED_ON,
    CMD_PWM_SET,
    CMD_SERVO_ATTACH,
    CMD_SERVO_DETACH,
    CMD_SERVO_SET_ANGLE,
    CMD_SET_LOG_LEVEL,
    CMD_SET_MODE,
    CMD_SET_VEL,
    CMD_STEPPER_ENABLE,
    CMD_STEPPER_MOVE_REL,
    CMD_STEPPER_STOP,
    CMD_STOP,
    CMD_TELEM_SET_INTERVAL,
    CMD_ULTRASONIC_ATTACH,
    CMD_ULTRASONIC_READ,
]
