# AUTO-GENERATED FILE — DO NOT EDIT BY HAND
# Generated from COMMANDS in platform_schema.py

CMD_ACTIVATE = "CMD_ACTIVATE"
CMD_ARM = "CMD_ARM"
CMD_CLEAR_ESTOP = "CMD_CLEAR_ESTOP"
CMD_CTRL_SET_RATE = "CMD_CTRL_SET_RATE"
CMD_CTRL_SIGNALS_CLEAR = "CMD_CTRL_SIGNALS_CLEAR"
CMD_CTRL_SIGNALS_LIST = "CMD_CTRL_SIGNALS_LIST"
CMD_CTRL_SIGNAL_DEFINE = "CMD_CTRL_SIGNAL_DEFINE"
CMD_CTRL_SIGNAL_DELETE = "CMD_CTRL_SIGNAL_DELETE"
CMD_CTRL_SIGNAL_GET = "CMD_CTRL_SIGNAL_GET"
CMD_CTRL_SIGNAL_SET = "CMD_CTRL_SIGNAL_SET"
CMD_CTRL_SLOT_CONFIG = "CMD_CTRL_SLOT_CONFIG"
CMD_CTRL_SLOT_ENABLE = "CMD_CTRL_SLOT_ENABLE"
CMD_CTRL_SLOT_RESET = "CMD_CTRL_SLOT_RESET"
CMD_CTRL_SLOT_SET_PARAM = "CMD_CTRL_SLOT_SET_PARAM"
CMD_CTRL_SLOT_SET_PARAM_ARRAY = "CMD_CTRL_SLOT_SET_PARAM_ARRAY"
CMD_CTRL_SLOT_STATUS = "CMD_CTRL_SLOT_STATUS"
CMD_DC_SET_SPEED = "CMD_DC_SET_SPEED"
CMD_DC_SET_VEL_GAINS = "CMD_DC_SET_VEL_GAINS"
CMD_DC_SET_VEL_TARGET = "CMD_DC_SET_VEL_TARGET"
CMD_DC_STOP = "CMD_DC_STOP"
CMD_DC_VEL_PID_ENABLE = "CMD_DC_VEL_PID_ENABLE"
CMD_DEACTIVATE = "CMD_DEACTIVATE"
CMD_DISARM = "CMD_DISARM"
CMD_ENCODER_ATTACH = "CMD_ENCODER_ATTACH"
CMD_ENCODER_READ = "CMD_ENCODER_READ"
CMD_ENCODER_RESET = "CMD_ENCODER_RESET"
CMD_ESTOP = "CMD_ESTOP"
CMD_GET_RATES = "CMD_GET_RATES"
CMD_GPIO_READ = "CMD_GPIO_READ"
CMD_GPIO_REGISTER_CHANNEL = "CMD_GPIO_REGISTER_CHANNEL"
CMD_GPIO_TOGGLE = "CMD_GPIO_TOGGLE"
CMD_GPIO_WRITE = "CMD_GPIO_WRITE"
CMD_HEARTBEAT = "CMD_HEARTBEAT"
CMD_LED_OFF = "CMD_LED_OFF"
CMD_LED_ON = "CMD_LED_ON"
CMD_OBSERVER_CONFIG = "CMD_OBSERVER_CONFIG"
CMD_OBSERVER_ENABLE = "CMD_OBSERVER_ENABLE"
CMD_OBSERVER_RESET = "CMD_OBSERVER_RESET"
CMD_OBSERVER_SET_PARAM = "CMD_OBSERVER_SET_PARAM"
CMD_OBSERVER_SET_PARAM_ARRAY = "CMD_OBSERVER_SET_PARAM_ARRAY"
CMD_OBSERVER_STATUS = "CMD_OBSERVER_STATUS"
CMD_PWM_SET = "CMD_PWM_SET"
CMD_SAFETY_SET_RATE = "CMD_SAFETY_SET_RATE"
CMD_SERVO_ATTACH = "CMD_SERVO_ATTACH"
CMD_SERVO_DETACH = "CMD_SERVO_DETACH"
CMD_SERVO_SET_ANGLE = "CMD_SERVO_SET_ANGLE"
CMD_SET_LOG_LEVEL = "CMD_SET_LOG_LEVEL"
CMD_SET_MODE = "CMD_SET_MODE"
CMD_SET_VEL = "CMD_SET_VEL"
CMD_STEPPER_ENABLE = "CMD_STEPPER_ENABLE"
CMD_STEPPER_MOVE_REL = "CMD_STEPPER_MOVE_REL"
CMD_STEPPER_STOP = "CMD_STEPPER_STOP"
CMD_STOP = "CMD_STOP"
CMD_TELEM_SET_INTERVAL = "CMD_TELEM_SET_INTERVAL"
CMD_TELEM_SET_RATE = "CMD_TELEM_SET_RATE"
CMD_ULTRASONIC_ATTACH = "CMD_ULTRASONIC_ATTACH"
CMD_ULTRASONIC_READ = "CMD_ULTRASONIC_READ"

ALL_COMMANDS = [
    CMD_ACTIVATE,
    CMD_ARM,
    CMD_CLEAR_ESTOP,
    CMD_CTRL_SET_RATE,
    CMD_CTRL_SIGNALS_CLEAR,
    CMD_CTRL_SIGNALS_LIST,
    CMD_CTRL_SIGNAL_DEFINE,
    CMD_CTRL_SIGNAL_DELETE,
    CMD_CTRL_SIGNAL_GET,
    CMD_CTRL_SIGNAL_SET,
    CMD_CTRL_SLOT_CONFIG,
    CMD_CTRL_SLOT_ENABLE,
    CMD_CTRL_SLOT_RESET,
    CMD_CTRL_SLOT_SET_PARAM,
    CMD_CTRL_SLOT_SET_PARAM_ARRAY,
    CMD_CTRL_SLOT_STATUS,
    CMD_DC_SET_SPEED,
    CMD_DC_SET_VEL_GAINS,
    CMD_DC_SET_VEL_TARGET,
    CMD_DC_STOP,
    CMD_DC_VEL_PID_ENABLE,
    CMD_DEACTIVATE,
    CMD_DISARM,
    CMD_ENCODER_ATTACH,
    CMD_ENCODER_READ,
    CMD_ENCODER_RESET,
    CMD_ESTOP,
    CMD_GET_RATES,
    CMD_GPIO_READ,
    CMD_GPIO_REGISTER_CHANNEL,
    CMD_GPIO_TOGGLE,
    CMD_GPIO_WRITE,
    CMD_HEARTBEAT,
    CMD_LED_OFF,
    CMD_LED_ON,
    CMD_OBSERVER_CONFIG,
    CMD_OBSERVER_ENABLE,
    CMD_OBSERVER_RESET,
    CMD_OBSERVER_SET_PARAM,
    CMD_OBSERVER_SET_PARAM_ARRAY,
    CMD_OBSERVER_STATUS,
    CMD_PWM_SET,
    CMD_SAFETY_SET_RATE,
    CMD_SERVO_ATTACH,
    CMD_SERVO_DETACH,
    CMD_SERVO_SET_ANGLE,
    CMD_SET_LOG_LEVEL,
    CMD_SET_MODE,
    CMD_SET_VEL,
    CMD_STEPPER_ENABLE,
    CMD_STEPPER_MOVE_REL,
    CMD_STEPPER_STOP,
    CMD_STOP,
    CMD_TELEM_SET_INTERVAL,
    CMD_TELEM_SET_RATE,
    CMD_ULTRASONIC_ATTACH,
    CMD_ULTRASONIC_READ,
]
