from robot_host.command.client import AsyncRobotClient
from robot_host.core.event_bus import EventBus


class ModeHostModule:
    """Wrapper for CMD_SET_MODE (IDLE / ARMED / ACTIVE / ESTOP).

    Uses the autogenerated cmd_set_mode() on AsyncRobotClient.
    """

    def __init__(self, bus: EventBus, client: AsyncRobotClient) -> None:
        self._bus = bus
        self._client = client

    async def set_mode(self, mode: str) -> None:
        await self._client.cmd_set_mode(mode=mode)

