from robot_host.command.client import AsyncRobotClient
from robot_host.core.event_bus import EventBus


class TelemetryControlModule:
    """Host-side helper for CMD_TELEM_SET_INTERVAL.

    Wraps the autogenerated cmd_telem_set_interval() on AsyncRobotClient.
    """

    def __init__(self, bus: EventBus, client: AsyncRobotClient) -> None:
        self._bus = bus
        self._client = client

    async def set_interval(self, interval_ms: int) -> None:
        await self._client.cmd_telem_set_interval(interval_ms=int(interval_ms))
